# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoStream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoStream.proto',
  package='protoStream',
  serialized_pb=_b('\n\x11protoStream.proto\x12\x0bprotoStream\"0\n\x11\x41pplicationHeader\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\"|\n\x11ProtoStreamHeader\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x1a\n\x12\x64\x65\x66\x61ult_entry_type\x18\x02 \x02(\t\x12:\n\x12\x61pplication_header\x18\x03 \x03(\x0b\x32\x1e.protoStream.ApplicationHeader\"\x94\x01\n\x14ProtoStreamDelimiter\x12L\n\x0e\x64\x65limiter_type\x18\x01 \x01(\x0e\x32/.protoStream.ProtoStreamDelimiter.DelimiterType:\x03\x45ND\".\n\rDelimiterType\x12\t\n\x05\x45NTRY\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x12\t\n\x05INDEX\x10\x03\x42\'\n\x18\x63om.spinn3r.api.protobufB\x0bProtoStream')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROTOSTREAMDELIMITER_DELIMITERTYPE = _descriptor.EnumDescriptor(
  name='DelimiterType',
  full_name='protoStream.ProtoStreamDelimiter.DelimiterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENTRY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDEX', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=359,
)
_sym_db.RegisterEnumDescriptor(_PROTOSTREAMDELIMITER_DELIMITERTYPE)


_APPLICATIONHEADER = _descriptor.Descriptor(
  name='ApplicationHeader',
  full_name='protoStream.ApplicationHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protoStream.ApplicationHeader.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='protoStream.ApplicationHeader.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=82,
)


_PROTOSTREAMHEADER = _descriptor.Descriptor(
  name='ProtoStreamHeader',
  full_name='protoStream.ProtoStreamHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='protoStream.ProtoStreamHeader.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_entry_type', full_name='protoStream.ProtoStreamHeader.default_entry_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='application_header', full_name='protoStream.ProtoStreamHeader.application_header', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=208,
)


_PROTOSTREAMDELIMITER = _descriptor.Descriptor(
  name='ProtoStreamDelimiter',
  full_name='protoStream.ProtoStreamDelimiter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='delimiter_type', full_name='protoStream.ProtoStreamDelimiter.delimiter_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOSTREAMDELIMITER_DELIMITERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=359,
)

_PROTOSTREAMHEADER.fields_by_name['application_header'].message_type = _APPLICATIONHEADER
_PROTOSTREAMDELIMITER.fields_by_name['delimiter_type'].enum_type = _PROTOSTREAMDELIMITER_DELIMITERTYPE
_PROTOSTREAMDELIMITER_DELIMITERTYPE.containing_type = _PROTOSTREAMDELIMITER
DESCRIPTOR.message_types_by_name['ApplicationHeader'] = _APPLICATIONHEADER
DESCRIPTOR.message_types_by_name['ProtoStreamHeader'] = _PROTOSTREAMHEADER
DESCRIPTOR.message_types_by_name['ProtoStreamDelimiter'] = _PROTOSTREAMDELIMITER

ApplicationHeader = _reflection.GeneratedProtocolMessageType('ApplicationHeader', (_message.Message,), dict(
  DESCRIPTOR = _APPLICATIONHEADER,
  __module__ = 'protoStream_pb2'
  # @@protoc_insertion_point(class_scope:protoStream.ApplicationHeader)
  ))
_sym_db.RegisterMessage(ApplicationHeader)

ProtoStreamHeader = _reflection.GeneratedProtocolMessageType('ProtoStreamHeader', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTREAMHEADER,
  __module__ = 'protoStream_pb2'
  # @@protoc_insertion_point(class_scope:protoStream.ProtoStreamHeader)
  ))
_sym_db.RegisterMessage(ProtoStreamHeader)

ProtoStreamDelimiter = _reflection.GeneratedProtocolMessageType('ProtoStreamDelimiter', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSTREAMDELIMITER,
  __module__ = 'protoStream_pb2'
  # @@protoc_insertion_point(class_scope:protoStream.ProtoStreamDelimiter)
  ))
_sym_db.RegisterMessage(ProtoStreamDelimiter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.spinn3r.api.protobufB\013ProtoStream'))
# @@protoc_insertion_point(module_scope)
