# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wikipedia.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wikipedia.proto',
  package='Wikipedia',
  serialized_pb=_b('\n\x0fwikipedia.proto\x12\tWikipedia\"\x96\x01\n\rWikipediaPage\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\x05\x12\x10\n\x08redirect\x18\x04 \x01(\t\x12\x14\n\x0crestrictions\x18\x05 \x01(\t\x12/\n\trevisions\x18\x06 \x03(\x0b\x32\x1c.Wikipedia.WikipediaRevision\"\xe4\x01\n\x11WikipediaRevision\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontributor\x18\x03 \x01(\t\x12\r\n\x05minor\x18\x04 \x01(\x08\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12\x0c\n\x04\x64iff\x18\x06 \x01(\t\x12\x0c\n\x04sha1\x18\x07 \x01(\t\x12\x11\n\tparent_id\x18\x08 \x01(\x05\x12\x13\n\x0bprevious_id\x18\t \x01(\x05\x12\r\n\x05model\x18\n \x01(\t\x12\x0e\n\x06\x66ormat\x18\x0b \x01(\t\x12\x17\n\x0f\x62\x65ginningofpage\x18\x0c \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WIKIPEDIAPAGE = _descriptor.Descriptor(
  name='WikipediaPage',
  full_name='Wikipedia.WikipediaPage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Wikipedia.WikipediaPage.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='Wikipedia.WikipediaPage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='Wikipedia.WikipediaPage.namespace', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='redirect', full_name='Wikipedia.WikipediaPage.redirect', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='restrictions', full_name='Wikipedia.WikipediaPage.restrictions', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='revisions', full_name='Wikipedia.WikipediaPage.revisions', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=181,
)


_WIKIPEDIAREVISION = _descriptor.Descriptor(
  name='WikipediaRevision',
  full_name='Wikipedia.WikipediaRevision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Wikipedia.WikipediaRevision.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='Wikipedia.WikipediaRevision.time_stamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contributor', full_name='Wikipedia.WikipediaRevision.contributor', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minor', full_name='Wikipedia.WikipediaRevision.minor', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='Wikipedia.WikipediaRevision.comment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diff', full_name='Wikipedia.WikipediaRevision.diff', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sha1', full_name='Wikipedia.WikipediaRevision.sha1', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='Wikipedia.WikipediaRevision.parent_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='previous_id', full_name='Wikipedia.WikipediaRevision.previous_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='Wikipedia.WikipediaRevision.model', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='Wikipedia.WikipediaRevision.format', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beginningofpage', full_name='Wikipedia.WikipediaRevision.beginningofpage', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=412,
)

_WIKIPEDIAPAGE.fields_by_name['revisions'].message_type = _WIKIPEDIAREVISION
DESCRIPTOR.message_types_by_name['WikipediaPage'] = _WIKIPEDIAPAGE
DESCRIPTOR.message_types_by_name['WikipediaRevision'] = _WIKIPEDIAREVISION

WikipediaPage = _reflection.GeneratedProtocolMessageType('WikipediaPage', (_message.Message,), dict(
  DESCRIPTOR = _WIKIPEDIAPAGE,
  __module__ = 'wikipedia_pb2'
  # @@protoc_insertion_point(class_scope:Wikipedia.WikipediaPage)
  ))
_sym_db.RegisterMessage(WikipediaPage)

WikipediaRevision = _reflection.GeneratedProtocolMessageType('WikipediaRevision', (_message.Message,), dict(
  DESCRIPTOR = _WIKIPEDIAREVISION,
  __module__ = 'wikipedia_pb2'
  # @@protoc_insertion_point(class_scope:Wikipedia.WikipediaRevision)
  ))
_sym_db.RegisterMessage(WikipediaRevision)


# @@protoc_insertion_point(module_scope)
